;
var $constants = (function () {
	'use strict';


	var constants = {
		'FETCH_BLOGERS_REQUESTED': 'FETCH_BLOGERS_REQUESTED',
		'FETCH_BLOGERS_SUCCEEDED': 'FETCH_BLOGERS_SUCCEEDED',
		'FETCH_BLOGERS_FAILED': 'FETCH_BLOGERS_FAILED',
		'FETCH_BLOGERS_UPDATE_START': 'FETCH_BLOGERS_UPDATE_START',
		'FETCH_BLOGERS_UPDATE_END': 'FETCH_BLOGERS_UPDATE_END',

		'RENDER_BLOGER_CARD_START': 'RENDER_BLOGER_CARD_START',
		'RENDER_BLOGER_CARD_END': 'RENDER_BLOGER_CARD_END',

		'RENDER_PAGINATION_START': 'RENDER_PAGINATION_START',
		'RENDER_PAGINATION_END': 'RENDER_PAGINATION_END',

		'SET_PAGINATION_METADATA_REQUESTED': 'SET_PAGINATION_METADATA_REQUESTED',
		'SET_PAGINATION_METADATA_START': 'SET_PAGINATION_METADATA_START',
		'SET_PAGINATION_METADATA_END': 'SET_PAGINATION_METADATA_END',

		'SET_CURRENT_PAGE_REQUESTED': 'SET_CURRENT_PAGE_REQUESTED',
		'SET_CURRENT_PAGE_START': 'SET_CURRENT_PAGE_START',
		'SET_CURRENT_PAGE_END': 'SET_CURRENT_PAGE_END',

		'SET_CARD_ANIMATION_START': 'SET_CARD_ANIMATION_START',
		'SET_CARD_ANIMATION_END': 'SET_CARD_ANIMATION_END'
	};

	return constants;

})();
