;
var $constants = (function () {
	'use strict';


	var constants = {
		'FETCH_BLOGERS_REQUESTED': 'FETCH_BLOGERS_REQUESTED',
		'FETCH_BLOGERS_SUCCEEDED': 'FETCH_BLOGERS_SUCCEEDED',
		'FETCH_BLOGERS_FAILED': 'FETCH_BLOGERS_FAILED',
		'FETCH_BLOGERS_UPDATED': 'FETCH_BLOGERS_UPDATED',

		'RENDER_BLOGER_CARD': 'RENDER_BLOGER_CARD',

		'RENDER_PAGINATION': 'RENDER_PAGINATION'
	};

	return constants;

})();
