;
var $constants = (function () {
	'use strict';


	var constants = {
		'FETCH_LAZY_ITEMS_REQUESTED': 'FETCH_LAZY_ITEMS_REQUESTED',
		'FETCH_LAZY_ITEMS_SUCCEEDED': 'FETCH_LAZY_ITEMS_SUCCEEDED',
		'FETCH_LAZY_ITEMS_FAILED': 'FETCH_LAZY_ITEMS_FAILED',
		'FETCH_LAZY_ITEMS_UPDATE_START': 'FETCH_LAZY_ITEMS_UPDATE_START',
		'FETCH_LAZY_ITEMS_UPDATE_END': 'FETCH_LAZY_ITEMS_UPDATE_END',

		'RENDER_CARD_START': 'RENDER_CARD_START',
		'RENDER_CARD_END': 'RENDER_CARD_END',

		'RENDER_PAGINATION_START': 'RENDER_PAGINATION_START',
		'RENDER_PAGINATION_END': 'RENDER_PAGINATION_END',

		'SET_PAGINATION_METADATA_REQUESTED': 'SET_PAGINATION_METADATA_REQUESTED',
		'SET_PAGINATION_METADATA_START': 'SET_PAGINATION_METADATA_START',
		'SET_PAGINATION_METADATA_END': 'SET_PAGINATION_METADATA_END',

		'SET_CURRENT_PAGE_REQUESTED': 'SET_CURRENT_PAGE_REQUESTED',
		'SET_CURRENT_PAGE_START': 'SET_CURRENT_PAGE_START',
		'SET_CURRENT_PAGE_END': 'SET_CURRENT_PAGE_END',

		'SET_CARD_ANIMATION_START': 'SET_CARD_ANIMATION_START',
		'SET_CARD_ANIMATION_END': 'SET_CARD_ANIMATION_END',

		'OPEN_MODAL_WINDOW_START': 'OPEN_MODAL_WINDOW_START',
		'OPEN_MODAL_WINDOW_END': 'OPEN_MODAL_WINDOW_END',
		'CLOSE_MODAL_WINDOW_START': 'CLOSE_MODAL_WINDOW_START',
		'CLOSE_MODAL_WINDOW_END': 'CLOSE_MODAL_WINDOW_END',

		'SET_ACTIVE_MODAL_WINDOW_START': 'SET_ACTIVE_MODAL_WINDOW_START',
		'SET_ACTIVE_MODAL_WINDOW_END': 'SET_ACTIVE_MODAL_WINDOW_END',
		'TAP_SEND_ORDER_BUTTON': 'TAP_SEND_ORDER_BUTTON',
		'WRITE_ORDER_DATA_START': 'WRITE_ORDER_DATA_START',
		'WRITE_ORDER_DATA_END': 'WRITE_ORDER_DATA_END',

		'VALIDATION_DATA_REQUESTED': 'VALIDATION_DATA_REQUESTED',
		'VALIDATION_DATA_SUCCEEDED': 'VALIDATION_DATA_SUCCEEDED',
		'VALIDATION_DATA_FAILED': 'VALIDATION_DATA_FAILED',

		'SEND_DATA_TO_SERVER_REQUESTED': 'SEND_DATA_TO_SERVER_REQUESTED',
		'SEND_DATA_TO_SERVER_START': 'SEND_DATA_TO_SERVER_START',
		'SEND_DATA_TO_SERVER_SUCCEEDED': 'SEND_DATA_TO_SERVER_SUCCEEDED',
		'SEND_DATA_TO_SERVER_FAILED': 'SEND_DATA_TO_SERVER_FAILED',

		'BLOCK_SEND_BUTTON_START': 'BLOCK_SEND_BUTTON_START',
		'BLOCK_SEND_BUTTON_END': 'BLOCK_SEND_BUTTON_END',
		'UNBLOCK_SEND_BUTTON_START': 'UNBLOCK_SEND_BUTTON_START',
		'UNBLOCK_SEND_BUTTON_END': 'UNBLOCK_SEND_BUTTON_END',

		'SUCCESS_ORDER_FINISHED': 'SUCCESS_ORDER_FINISHED'
	};

	return constants;

})();
